server:
  port: 8001

spring:
  application:
    name: cloud-payment-service # 服务名称

  zipkin: #<-------------------------------------关键
    base-url: http://localhost:9411
  sleuth: #<-------------------------------------关键
    sampler:
    #采样率值介于 0 到 1 之间，1 则表示全部采集
    probability: 1

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://106.14.157.213:3306/cloud2021?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Dinghaiting19980501@

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.dht.entity    # 所有Entity别名类所在包
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


eureka:
  client:
    #表示是否将自己注册进Eurekaserver默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #defaultZone:  http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka  # 入驻 eureka地址
      defaultZone:  http://eureka7001.com:7001/eureka  # 入驻 eureka地址
  instance:
    instance-id: payment8001  #添加此处
    prefer-ip-address: true #添加此处
      #心跳检测与续约时间
      #开发时没置小些，保证服务关闭后注册中心能即使剔除服务
      #Eureka客户端向服务端发送心跳的时间间隔，单位为秒(默认是30秒)
    lease-renewal-interval-in-seconds: 1
      #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒(默认是90秒)，超时将剔除服务
    lease-expiration-duration-in-seconds: 2
