server:
  port: 8002

spring:
  application:
    name: cloud-payment-service # 服务名称

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://106.14.157.213:3306/cloud2021?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Dinghaiting19980501@

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.dht.entity    # 所有Entity别名类所在包
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


eureka:
  client:
    #表示是否将自己注册进Eurekaserver默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #defaultZone:  http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka  # 入驻 eureka地址
      defaultZone:  http://eureka7001.com:7001/eureka  # 入驻 eureka地址
  instance:
    instance-id: payment8002  #添加此处
    prefer-ip-address: true #添加此处